// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevendaPro.Infrastructure.Database.Contexts;

#nullable disable

namespace RevendaPro.Infrastructure.Database.Migrations
{
    [DbContext(typeof(RevendaProDbContext))]
    partial class RevendaProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RevendaPro.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(13);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("NewValues")
                        .HasColumnType("json")
                        .HasColumnOrder(9);

                    b.Property<string>("OldValues")
                        .HasColumnType("json")
                        .HasColumnOrder(8);

                    b.Property<Guid>("RecordCode")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EntityName", "RecordCode");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(4);

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Position");

                    b.ToTable("ExpenseType", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.FipeQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(8);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(13);

                    b.Property<string>("FipeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(9);

                    b.Property<short>("ModelYear")
                        .HasColumnType("smallint")
                        .HasColumnOrder(7);

                    b.Property<DateOnly>("ReferenceMonth")
                        .HasColumnType("date")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(14);

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(6);

                    b.Property<string>("YearFuel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FipeCode", "YearFuel", "ReferenceMonth")
                        .IsUnique();

                    b.ToTable("FipeQuote", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(6);

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(20);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(19);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(17);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(14);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(13);

                    b.Property<decimal?>("PartnerCutAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(11);

                    b.Property<decimal?>("PartnerCutPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(10);

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("ProspectName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnOrder(4);

                    b.Property<string>("ProspectPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(5);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(12);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(18);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdVehicle", "Status");

                    b.ToTable("Proposal", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(4);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RoleScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("IdScreen")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdScreen");

                    b.HasIndex("IdRole", "IdScreen")
                        .IsUnique();

                    b.ToTable("RoleScreen", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(7);

                    b.Property<string>("BuyerDocument")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnOrder(16);

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnOrder(15);

                    b.Property<string>("BuyerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(17);

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Commission")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(13);

                    b.Property<string>("CommissionNotes")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(14);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(22);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnOrder(6);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(26);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(21);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(23);

                    b.Property<int?>("IdProposal")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int?>("IdTradeInVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(20);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(19);

                    b.Property<decimal?>("PartnerCutAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(12);

                    b.Property<decimal?>("PartnerCutPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(11);

                    b.Property<string>("PartnerStoreName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnOrder(10);

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<decimal?>("TradeInValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(18);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(24);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Date");

                    b.HasIndex("IdProposal");

                    b.HasIndex("IdTradeInVehicle");

                    b.HasIndex("IdVehicle");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(17);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(14);

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(7);

                    b.Property<int?>("IdParentScreen")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(11);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(4);

                    b.Property<string>("MenuGroup")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(5);

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(6);

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdParentScreen");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MenuGroup", "Order");

                    b.ToTable("Screen", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(6);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(17);

                    b.Property<string>("Document")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(14);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(11);

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(4);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(6);

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnOrder(9);

                    b.Property<string>("Photo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(7);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser", "IdRole")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("AdvertisedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(33);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(7);

                    b.Property<decimal?>("BudgetCeiling")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(25);

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnOrder(12);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(38);

                    b.Property<string>("DamageDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(19);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(42);

                    b.Property<decimal?>("DesiredNetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(31);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(37);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(41);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(39);

                    b.Property<string>("FipeCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(28);

                    b.Property<DateOnly?>("FipeReferenceDate")
                        .HasColumnType("date")
                        .HasColumnOrder(27);

                    b.Property<int?>("FipeSource")
                        .HasColumnType("int")
                        .HasColumnOrder(30);

                    b.Property<decimal?>("FipeValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(26);

                    b.Property<string>("FipeYearFuel")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(29);

                    b.Property<int>("FuelType")
                        .HasColumnType("int")
                        .HasColumnOrder(14);

                    b.Property<bool>("HasDamage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(18);

                    b.Property<int?>("IdCoverPhoto")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(36);

                    b.Property<short>("ManufactureYear")
                        .HasColumnType("smallint")
                        .HasColumnOrder(11);

                    b.Property<string>("MarketNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnOrder(34);

                    b.Property<int>("Mileage")
                        .HasColumnType("int")
                        .HasColumnOrder(13);

                    b.Property<decimal?>("MinimumNetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(32);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(8);

                    b.Property<short>("ModelYear")
                        .HasColumnType("smallint")
                        .HasColumnOrder(10);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnOrder(35);

                    b.Property<int>("Origin")
                        .HasColumnType("int")
                        .HasColumnOrder(17);

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnOrder(5);

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnOrder(22);

                    b.Property<int?>("PurchasePaymentMethod")
                        .HasColumnType("int")
                        .HasColumnOrder(24);

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(21);

                    b.Property<string>("Renavam")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnOrder(16);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(20);

                    b.Property<string>("SupplierName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(23);

                    b.Property<int>("Transmission")
                        .HasColumnType("int")
                        .HasColumnOrder(15);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(40);

                    b.Property<string>("Version")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Chassis");

                    b.HasIndex("IdTenant", "Plate");

                    b.HasIndex("IdTenant", "Status");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(7);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(15);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(6);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(9);

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("SizeInBytes")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdVehicle");

                    b.ToTable("VehicleDocument", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(13);

                    b.Property<int>("IdExpenseType")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(9);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnOrder(8);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdExpenseType");

                    b.HasIndex("IdVehicle");

                    b.ToTable("VehicleExpense", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehiclePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(17);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(14);

                    b.Property<short>("Height")
                        .HasColumnType("smallint")
                        .HasColumnOrder(9);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(11);

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<int>("SizeInBytes")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(15);

                    b.Property<short>("Width")
                        .HasColumnType("smallint")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdVehicle", "Position");

                    b.ToTable("VehiclePhoto", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<string>("Reason")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnOrder(6);

                    b.Property<int>("ToStatus")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdVehicle");

                    b.ToTable("VehicleStatusHistory", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.ExpenseType", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Proposal", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Role", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RoleScreen", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevendaPro.Domain.Entities.Screen", null)
                        .WithMany()
                        .HasForeignKey("IdScreen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Sale", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Proposal", null)
                        .WithMany()
                        .HasForeignKey("IdProposal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdTradeInVehicle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Screen", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Screen", null)
                        .WithMany()
                        .HasForeignKey("IdParentScreen")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.User", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevendaPro.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleExpense", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.ExpenseType", null)
                        .WithMany()
                        .HasForeignKey("IdExpenseType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehiclePhoto", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.VehicleStatusHistory", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
