// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevendaPro.Infrastructure.Database.Contexts;

#nullable disable

namespace RevendaPro.Infrastructure.Database.Migrations
{
    [DbContext(typeof(RevendaProDbContext))]
    partial class RevendaProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RevendaPro.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(13);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("NewValues")
                        .HasColumnType("json")
                        .HasColumnOrder(9);

                    b.Property<string>("OldValues")
                        .HasColumnType("json")
                        .HasColumnOrder(8);

                    b.Property<Guid>("RecordCode")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EntityName", "RecordCode");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(4);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(4);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RoleScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("IdScreen")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdScreen");

                    b.HasIndex("IdRole", "IdScreen")
                        .IsUnique();

                    b.ToTable("RoleScreen", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(13);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(17);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(14);

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(7);

                    b.Property<int?>("IdParentScreen")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(11);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(4);

                    b.Property<string>("MenuGroup")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(5);

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(6);

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdParentScreen");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MenuGroup", "Order");

                    b.ToTable("Screen", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(6);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(10);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(3);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(12);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(16);

                    b.Property<string>("Document")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(13);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnOrder(5);

                    b.Property<int>("IdTenant")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnOrder(4);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(6);

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnOrder(9);

                    b.Property<string>("Photo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnOrder(7);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdTenant", "Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(7);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DtDeleted")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("DtUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(8);

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser", "IdRole")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Role", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.RoleScreen", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevendaPro.Domain.Entities.Screen", null)
                        .WithMany()
                        .HasForeignKey("IdScreen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.Screen", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Screen", null)
                        .WithMany()
                        .HasForeignKey("IdParentScreen")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.User", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RevendaPro.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("RevendaPro.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevendaPro.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
